#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OrderRecord {
    pub id: i64,
    pub oddnumber: String,
    pub billing_at: i64,
    pub consignee: String,
    pub consigneephone: String,
    pub address: String,
    pub method: String,
    pub goodsname: String,
    pub number: String,
    pub pack: String,
    pub weight: String,
    pub measurement: String,
    pub cainsurance: String,
    pub value: String,
    pub insurance: String,
    pub consignor: String,
    pub consignorphone: String,
    pub freight: String,
    pub delivery: String,
    pub sumfreight: String,
    pub freightstate: String,
    pub paynow: String,
    pub paygo: String,
    pub payback: String,
    pub paymonth: String,
    pub receiptnum: i64,
    pub company: String,
    pub remarks: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReceiptRecord {
    pub id: i64,
    pub oddnumber: String,
    pub billing_at: i64,
    pub recoverystate: String,
    pub issuestate: String,
    pub poststate: String,
    pub recoverynumber: i64,
    pub consignor: String,
    pub consignee: String,
    pub goodsname: String,
    pub goodsnumber: String,
}

impl OrderRecord {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        id: i64,
        oddnumber: impl Into<String>,
        billing_at: i64,
        consignee: impl Into<String>,
        consigneephone: impl Into<String>,
        address: impl Into<String>,
        method: impl Into<String>,
        goodsname: impl Into<String>,
        number: impl Into<String>,
        pack: impl Into<String>,
        weight: impl Into<String>,
        measurement: impl Into<String>,
        cainsurance: impl Into<String>,
        value: impl Into<String>,
        insurance: impl Into<String>,
        consignor: impl Into<String>,
        consignorphone: impl Into<String>,
        freight: impl Into<String>,
        delivery: impl Into<String>,
        sumfreight: impl Into<String>,
        freightstate: impl Into<String>,
        paynow: impl Into<String>,
        paygo: impl Into<String>,
        payback: impl Into<String>,
        paymonth: impl Into<String>,
        receiptnum: i64,
        company: impl Into<String>,
        remarks: impl Into<String>,
    ) -> Self {
        Self {
            id,
            oddnumber: oddnumber.into(),
            billing_at,
            consignee: consignee.into(),
            consigneephone: consigneephone.into(),
            address: address.into(),
            method: method.into(),
            goodsname: goodsname.into(),
            number: number.into(),
            pack: pack.into(),
            weight: weight.into(),
            measurement: measurement.into(),
            cainsurance: cainsurance.into(),
            value: value.into(),
            insurance: insurance.into(),
            consignor: consignor.into(),
            consignorphone: consignorphone.into(),
            freight: freight.into(),
            delivery: delivery.into(),
            sumfreight: sumfreight.into(),
            freightstate: freightstate.into(),
            paynow: paynow.into(),
            paygo: paygo.into(),
            payback: payback.into(),
            paymonth: paymonth.into(),
            receiptnum,
            company: company.into(),
            remarks: remarks.into(),
        }
    }
}

impl ReceiptRecord {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        id: i64,
        oddnumber: impl Into<String>,
        billing_at: i64,
        recoverystate: impl Into<String>,
        issuestate: impl Into<String>,
        poststate: impl Into<String>,
        recoverynumber: i64,
        consignor: impl Into<String>,
        consignee: impl Into<String>,
        goodsname: impl Into<String>,
        goodsnumber: impl Into<String>,
    ) -> Self {
        Self {
            id,
            oddnumber: oddnumber.into(),
            billing_at,
            recoverystate: recoverystate.into(),
            issuestate: issuestate.into(),
            poststate: poststate.into(),
            recoverynumber,
            consignor: consignor.into(),
            consignee: consignee.into(),
            goodsname: goodsname.into(),
            goodsnumber: goodsnumber.into(),
        }
    }
}
